@baseUrl=http://localhost:3000
POST http://localhost:3000/auth/admin/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0ODEyZjE1LTc2ZmItNDkwYS1iMjZmLTAyMmUzNjg1MmI4YSIsIm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkSGFzaCI6IiQyYiQxMCRBZGlDRDRCaWRSUzBnay5zUlB3YmQuREFsalR1MXFFTUdFdnViUTBobk90ekFHdncxdER4TyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY2NTY4NDAyMn0._I1YLG6hFwKtfZ3W7c3vo0r_aSATOiwFMWRa-uUb9oU

{
  "name": "admin",
  "password":"admin123"
}
###
POST http://localhost:3000/auth/user/login
Content-Type: application/json

{
  "name": "user",
  "password":"user123"
}

###
POST http://localhost:3000/auth/create/user
Content-Type: application/json

{
  "name": "DHRUV",
  "password":"user123"
}